### PR TITLE
Update datamanager.config for NV / MV

### PR DESCRIPTION
**Pull request by JoranAngevaare**
Since https://github.com/XENONnT/straxen/pull/287 we have another raw_record type: 
`raw_records_aux_mv` we might also want to track this in admix.

Additionally, we should start setting up the NV admix handling. This means removing `raw_records_nv` from this list and changing it with `raw_records_coin_nv`. The `raw_records_nv` will be deleted by `ajax`: https://github.com/XENONnT/straxen/blob/master/bin/ajax#L265/

Furthermore, we might also want to setup the NV handling
1. `records_nv`
2. `records_mv`
3. `lone_raw_records_nv`
4. `lone_raw_record_statistics_nv`
5. `hitlets_nv` (optional? This is more or less peak level)
6. `hitlets_mv`  (optional? This is more or less peak level)

### CODE REVIEW

**Comment by JoranAngevaare** [comment]
Perhaps @lucascottolavina can correct me if I overlooked anything and/or this is the correct approach. I'm e.g. not sure where line 5. is used.

Also @feigaodm or another AC may comment or this is the right approach for moving the NV/MV data.

**Comment by lucascottolavina** [comment]
To me it's fine and the modification you have done is correct. Please note that you modified also "rawtype" that is actually deprecated. At a certain point, I have to get rid of the deprecated lines in the configuration file, to be done in parallel with the elimination of the old uploading tasks that now it is clear we will never use any more.
Let's remind that in those three lists (norecords_types, records_types and raw_records_types) the order is important since it determines the priority of data types uploading within that list.

**Comment by WenzDaniel** [comment]
Hej, thanks for pointing out this PR, but during commissioning we would like to keep raw_records_nv since we have to optimize the software trigger first. Hence the data_types we currently need are 

* raw_records_nv
* records_nv
* hitlets_nv

**Comment by lucascottolavina** [comment]
Please have a look at the latest modification. I have put back raw_records_nv, then added hitlets_mv and hitlets_nv. If we are all happy about it will validate it

**Comment by JoranAngevaare** [comment]
@lucascottolavina I'm fine with this but we will have to remove `raw_records_nv` at some point as we only want the `raw_records_nv_coincidence` tracked for long term storage. See https://xenonnt.slack.com/archives/C016UJZ090B/p1609248620089500.

**Pull request merged**
